shouya/rss-funnel

- src/filter.rs
- src/filter/full_text.rs
- src/filter/html.rs
- src/filter/js.rs
- src/filter/sanitize.rs
- src/filter/select.rs
- src/filter/simplify_html.rs
This PR changes the signature of the trait from:
``` rust
pub trait FeedFilterConfig: DeserializeOwned {
type Filter: FeedFilter;
async fn build(&self) -> Result<Self::Filter>;
}
```
to:
``` rust
pub trait FeedFilterConfig: DeserializeOwned {
type Filter: FeedFilter;
async fn build(self) -> Result<Self::Filter>;
}
```
The main reason to make the change is because the latter makes more sense. The config is supposed to be consumed when built into a filter. The former signature is confusing because it implies that the config may be used for other purpose after the build, or that the config may be built into a filter repeatedly. Either implication is not true about the expected use of the type.
> refactor(filters): change the signature of FeedFilterConfig::build

- src/filter.rs
- src/filter/highlight.rs
- src/html.rs
This filter is used to highlight keywords in an article. Currently only the body is highlighted.
The config syntax looks like this:
``` yaml
filters:
- highlight:
keywords: ["foo", "bar"]
bg_color: "#FFFF00"
```
or:
``` yaml
filters:
- highlight:
patterns: ["\d+ foo"]
bg_color: "#FFFF00"
```
- The `bg_color` field is optional and defaults to `#ffff00`.
- Either `keywords` or patterns are case-insensitive.
- The `keywords` does not only match on word boundary.
Each of the matching keyword will be surrounded by a `span` with the style set and the `class` attribute set to `rss-funnel-hl`.
> feat(filters): add highlighter filter

- Cargo.lock
- Cargo.toml
- src/client.rs
- src/client/cache.rs
- src/filter/full_text.rs
- src/filter/simplify_html.rs
- src/server/endpoint.rs
- src/util.rs
This PR implements a client that caches the get requests to the servers when fetching feeds. It is used in places where `reqwest::Client` is used. Currently there are two places:
- the client used to fetch the source (default ttl: 15 minutes)
- the full_text filter (default ttl: 12 hours)
This mechanism is expected to help in speeding up the fetching of feeds especially for repeated full-text requests.
I'm also planning to employ this cache tests to insert custom fixtures for certain web addresses for future feature tests.
> feat(client): Caching requests to servers for feed

- src/client.rs
- src/client/cache.rs
- src/server/endpoint.rs
Previously the `content_type` in endpoint config is used to enforce the interpretation of the request body in a certain content type. This feature is useful on some feeds that reports wrong content types.
Later I discovered that this feature is more generally needed. For example, in the upcoming merge filter, we may also want to assume the content_type for the merged source. So in this PR, I moved the `content_type` field from endpoint's config to the client's config. I also renamed it to `assume_content_type` to make it more clear.
BREAKING CHANGE: This change will break the existing configuration if you use `content_type` field in an endpoint. You need to update your endpoint config as follows:
``` yaml
endpoints:
- path: /foo
source: http://website/feed.xml
content_type: …
```
> fix(config)!: change content_type from endpoint config

- src/client.rs
- src/feed.rs
- src/filter.rs
- src/filter/merge.rs
- src/server/endpoint.rs
- src/util.rs
Implements #11.
The new filter's name is `merge_feed` and the config type is either:
- an string, which is interpreted as the url of the source to merge
- or a full config object with the following properties:
- `source` (string, required): the source url of the extra feed
- `client` (string, optional): any Client config
- `filters` (string, optional): a list of filters to run on the extra feed before merging it
Here's an example config using the `merge_feed` filter:
``` yaml
endpoints:
- path: "/my-feed"
source: "https://example.com/feed"
filters:
- merge_feed: "https://example.com/extra-feed"
- path: "/my-feed"
source: "https://example.com/feed"
filters:
- merge_feed:
source: "https://example.com/extra-feed"
client:
timeout: 10
filters:
- full_text: {}
- js: |
function modify_post(feed, …
```
> feat(filters): new `merge_feed` filter

- src/client.rs
- src/client/cache.rs
- src/filter/js.rs
- src/filter/merge.rs
- src/test_utils.rs
previous approach to read from fixture by inserting fixture files into the cache of the client was not working for two reasons:
- the dummy client is only constructed for the source client, which means other requests like the one used in `merge_feed` filter can't use the fixtures.
- the cache has its own purpose and should be considered orthogonal to the fixtures, as it's consider an internal logic of the client. It's not a good idea to rely on the cache for providing fixtures for testing.
This commit changes the approach to read from fixture files by requesting with `fixtures://` scheme, which is then handled by a custom adapter that reads the file from the fixture directory. Note, the `fixtures://` scheme is only handled in test environment.
> test: read from fixture directory

- src/js/dom.rs
This pull request adds the following DOM manipulation methods to the `Node` class.
- `Node.previous_sibling()`: returns the previous sibling of the node
- `Node.next_sibling()`: returns the next sibling of the node
- `Node.parent()`: returns the parent of the node
- `Node.node_type()` returns the type of the node (one of "text", "element", "other")
- `Node.destroy()`: removes the node from the DOM
Fixes #14.
> feat(js): add more DOM manipulation methods to the `Node` class

- README.org
By default app listen on 127.0.0.1:4080 which is unreachable outside container, even with exposed port
Closes #4
> fix bind adress in docker compose example

- src/server.rs
This PR adds a new boolean flag to `server` subcommand: `--inspector-ui=<true|false>`.
The flag is by default set to `true` and can be set to `false` to disable inspector UI.
With the inspector disabled, the index page will simply show a message indicating the instance is running.
> feat(inspector-ui): add an option to disable inspector ui

- Cargo.lock
- Cargo.toml
- src/cli.rs
- src/server.rs
This PR implements the auto-reload feature for the server. When the server is running with `-w`/`--watch` flag, it will watch the config file and reload the server when the config file is modified.
> feat(server): auto reload server on config change

- Cargo.lock
- Cargo.toml
- inspector/src/FeedInspector.js
- inspector/src/index.html
- inspector/src/style.css
- src/server.rs
Add a reload button that reloads the config manually.
In the future I may implement this to be automatic, probably with a websocket connection to the backend to detect reload events. For the time being, I think this button is a simple and good enough solution.
In the passing I found a bug with the response in `_inspector/config` is not being updated when the config is reloaded. I fixed that as well.
> feat(inspector-ui): add a reload button

- inspector/src/FeedInspector.js
- inspector/src/index.html
- inspector/src/style.css
- src/cli.rs
- src/feed.rs
- src/filter/merge.rs
- src/main.rs
- src/server/endpoint.rs
- src/source.rs
- src/util.rs
Fixes #35.
Now it's possible to specify in the `source` field (under `endpoint`, or in `merge` filter's config) a struct that looks like this:
``` yaml
- path: /feed.xml
source:
format: rss # or atom
title: "My Feed"
description: "This is my feed"
link: "https://example.com/"
```
Don't forget to ensure the inspector ui has proper support for it before merging.
> feat: create feed from scratch

- src/filter.rs
- src/filter/full_text.rs
- src/filter/highlight.rs
- src/filter/html.rs
- src/filter/js.rs
- src/filter/merge.rs
- src/filter/sanitize.rs
- src/filter/select.rs
- src/filter/simplify_html.rs
- src/filter_pipeline.rs
- src/main.rs
- src/server/endpoint.rs
Prior to this change, the `FeedFilter` trait is defined as follows:
``` rust
pub trait FeedFilter {
async fn run(&self, feed: &mut Feed) -> Result<()>;
}
```
Now I want to change the `FeedFilter` trait to be as follows:
``` rust
pub trait FeedFilter {
async fn run(&self, ctx: &mut FilterContext, feed: Feed) -> Result<Feed>;
}
```
There are two major changes made to this interface.
First, the `run` method now takes a `FilterContext` that can be used to store and retrieve state. The can `FilterContext` is used to influence the behavior of filters. Currently no filter uses this context yet. But I plan to put the base address from the request to the context so that the `client` downstream can use this information to reconstruct absolute url from relative urls. (c.f. #36)
Secondly, I modified …
> refactor: FeedFilter trait

- src/cli.rs
- src/filter.rs
- src/filter/merge.rs
- src/filter_pipeline.rs
- src/server/endpoint.rs
- src/source.rs
Fix #36.
Note: this feature depends on correct `X-Forwarded-Host` and `X-Forwarded-Proto` headers.
> feat: specify local endpoints as source

- Cargo.lock
- Cargo.toml
- src/config.rs
- src/server.rs
- src/server/inspector.rs
The Inspector UI is now enabled by a feature flag named `inspector-ui`. The feature is by default enabled. One can disable it during in build time with `--no-default-filters` flag in `cargo build` command.
Fixes #33.
> feat: feature flag to disable inspector-ui on build time

- Cargo.lock
- Cargo.toml
- Cross.toml
- Makefile
Upgraded rquickjs to 0.5.1. Fixes #43.
> chore(build): fix build for aarch64-unknown-linux-gnu target

- src/filter.rs
- src/filter/note.rs
This filter allows you to add comments. Just insert a `note: <your comment>` line in the filter list.
The `note` filter does not affect the pipeline in any way, although it does count as a filter in the `limit_filters` setting.
Example:
```yaml
- path: /foo.xml
source: https://example.com/foo.xml
note: This is the note for the endpoint
filters:
- full_text: {}
- note: You can add a note filter to add comments to the pipeline.
- merge: https://example.com/bar.xml
- note: |
This is a multiline note.
It can be useful to add more detailed comments.
```
---------
An alternative approach I considered was to add a `note` field to all filters. However, this approach is limited because many filters are configured not as a struct. Often the case the config is just a single literal value, or a list …
> feat(filters): add `note` filter

- src/filter.rs
- src/filter/js.rs
Fixes https://github.com/shouya/rss-funnel/issues/38.
The config syntax looks like:
``` yaml
filters:
- modify_post: |
if (feed.title === 'Hacker News') {
post.title = post.title.replace('Show HN: ', '');
}
- modify_feed: feed.title = 'HN';
```
This implementation is quick and dirty as it merely template the code in `modify_post` and `modify_feed` like this:
``` javascript
function modify_post(feed, post) {
<your code>;
return post;
}
```
> feat(filters): add `modify_post` and `modify_feed` filters

- src/cli.rs
- src/client.rs
- src/config.rs
- src/feed.rs
- src/filter.rs
- src/filter/full_text.rs
- src/filter/highlight.rs
- src/filter/html.rs
- src/filter/js.rs
- src/filter/merge.rs
- src/filter/note.rs
- src/filter/sanitize.rs
- src/filter/select.rs
- src/filter/simplify_html.rs
- src/filter_pipeline.rs
- src/js.rs
- src/js/builtin.rs
- src/server.rs
- src/server/endpoint.rs
- src/server/feed_service.rs
- src/server/inspector.rs
- src/source.rs
- src/test_utils.rs
- src/util.rs
The purpose of this branch is to support partial reloading.
Now we will only:
- Only rebuild endpoints whose config changes
- Only rebuild filters whose config changes
If an endpoint's config was untouched, we will reuse the existing endpoint. Same for any filters in the filter pipeline.
There are several benefits with this approach:
- faster, more lightweight reload
- less disruption to caches (e.g. http client cache)
- the server does not need to be restarted on config change
- open up the possibility of notifying and reporting config error to inspector-ui
Aside from some logging changes, this branch should cause no functional difference.
------------
It's not trivial to implement this feature. Doing so requires some architectural change in the server implementation. Previously the …
> refactor(server): optimize reload logic

- src/filter/full_text.rs
- src/filter/html.rs
- src/util.rs
I realized the post processing of the fetched html page is a bottleneck for full_text filter. After profiling, I found:
- The post processing step in dev mode can take 100ms-400ms.
- Most of the computation were hidden inside `tendril` and `html5ever` libraries, which is not easily optimized from this crate.
- Even worse, the post-processing for each feed item was not parallelized. So the latency add up.
So in this patch I moved the compute intensive part into separate tokio tasks so they can be computed at the same time.
For reference, before the change, the sample hackernews full text endpoint [1] takes around 9s to finish. With the request caching, it still takes around 4s. After the change, the uncached version takes 4s and cached version only take less than 1s (on my 8-core machine). …
> perf(filters): parallelize feed post-processing

- inspector/src/FeedInspector.js
- inspector/src/Filter.js
- inspector/src/index.html
- inspector/src/style.css
- src/cli.rs
- src/config.rs
- src/server.rs
- src/server/feed_service.rs
- src/server/inspector.rs
This patch improves the display of feed error and adds the ability to show config error.
Screenshot showing both the config error and the feed error:
Fixes https://github.com/shouya/rss-funnel/issues/39.
> feat(inspector-ui): show config and feed error message

- Cargo.lock
- Cargo.toml
- inspector/package.json
- inspector/pnpm-lock.yaml
- inspector/src/FeedInspector.js
- inspector/src/index.html
- inspector/src/style.css
- inspector/src/util.js
- src/cli.rs
- src/feed.rs
- src/server.rs
- src/server/endpoint.rs
- src/server/feed_service.rs
- src/server/inspector.rs
- src/util.rs
Fixes https://github.com/shouya/rss-funnel/issues/53.
This pull request adds the feature to view the json representation of the feed, which can be manipulated in the `js` filter.
BREAKING CHANGE: the `pp=1` (pretty-print) query parameter on feed endpoints are no longer respected. The serialized feed will always be pretty-printed.
> feat(inspector-ui)!: show json preview for the feed

- src/client.rs
- src/feed.rs
- src/test_utils.rs
- src/util.rs
Fixes https://github.com/shouya/rss-funnel/issues/66.
Also, unknown feed types now raise an error than panicking.
> fix(endpoint): handle non-utf8 feeds correctly

- inspector/src/index.html
- inspector/src/style.css
- src/filter/js.rs
- src/js.rs
- src/js/builtin.rs
- src/js/dom.rs
- src/js/fetch.rs
- src/util.rs
This PR is to implement a simple fetch api for the JS runtime. It enables the user to request data from servers within any JavaScript code.
Here's the API:
``` typescript
type RequestParam = {
method: "GET" | "POST" | "PUT" | "DELETE",
headers: { [key: string]: string },
body: string?
}
fetch(url: string, params?: RequestParam): Promise<Response>;
class Response {
status: number,
headers: { [key: string]: string },
body: string | null
json(): Object
}
```
Here's a sample endpoint that returns de-clickbait-ed youtube feed using [DeArrow](https://github.com/ajayyy/DeArrow) service:
```yaml
- path: /kurtzgesagt-dearrow.xml
source: https://www.youtube.com/feeds/videos.xml?channel_id=UCsXVk37bltHxD1rDPwtNM8Q
filters:
- modify_post: |
const video_id = post.id.split(':').pop();
let resp = await …
```
> feat(js): implement fetch api for js runtime

- Cargo.lock
- Cargo.toml
- inspector/package.json
- inspector/src/FeedInspector.js
- inspector/src/index.html
- inspector/src/login.html
- inspector/src/style.css
- src/cli.rs
- src/server.rs
- src/server/auth.rs
- src/server/feed_service.rs
- src/server/inspector.rs
Fixes #56.
This pull request implements authentication support with a very simple login page:
You can specify a username and password in the config to protect the inspector UI behind the login page:
``` yaml
auth:
username: admin
password: hunter2
endpoints:
- ...
```
If the `auth` config is not specified, authentication will be disabled and the inspector UI is accessible publicly.
Note: the login feature is implemented in a very primitive way for the sake of the simplicity. Only one single user can be logged in at the same time. This means if if you try to log in from another browser, the existing session will be invalidated. Also, there is no session expiration mechanism. To log out, use the "Logout" button from the inspector UI, or simply clear your cookie.
> feat(inspector-ui): authentication support

- src/filter/js.rs
Previously, the user code is embedded in a function that looks like this:
``` javascript
async function modify_post(feed, post) {
<USER CODE>;
return post;
}
```
It means in the filter config, if the user wants to early return, they must call `return post;` explicitly. This is a little clumsy given we want to give the illusion that the user no longer has to explicitly return post or anything.
I hope to enable the user to write code like this in `modify_post` and `modify_feed` filter:
``` javascript
if (condition 1) {
// do no modify post by early return
return;
}
if (condition 2) {
// delete post by assigning it null;
post = null;
return;
}
if (condition 3) {
// alternatively, delete post by returning null
return null;
}
// normally edit the post
post.field = 'new value';
```
Because now …
> fix(filters): support early return in `modify_post` and `modify_feed`

- inspector/src/Filter.js
- inspector/src/style.css
The `note` filter's value is now rendered in variable pitch font inside a `<p>` tag instead of as json value.
> feat(inspector-ui): render note filter's value as documentation

- Cargo.toml
- src/cli.rs
- src/server.rs
- src/server/feed_service.rs
It's often more convenient to specify the server flags via environment
than overriding the default command line. This pull request adds the
ability to specify the server flags via environment.
Currently, the following environments are supported:
| Variable                  | Default value    | Description                                                         |
|---------------------------|------------------|---------------------------------------------------------------------|
| `RSS_FUNNEL_BIND`         | `127.0.0.1:4080` | The server bind address                                             |
| `RSS_FUNNEL_INSPECTOR_UI` | `true`           | Whether or not to serve the inspector UI                            |
| `RSS_FUNNEL_WATCH`        | `false`          | Whether or not to watch …
> feat(cli): specify server flags via environment

- src/filter/merge.rs
Previously, the `client` and `filters` fields were required (but has a default value). One So if the user don't specify the `client` and `filters` fields, they'll default to a struct with the default values.
One side effect is that the inspector-ui will try render the all-empty field for `client` even if the user didn't specify it `client` their config.
With this change, I wrapped the `client` and `filters` fields with `Option` box, so now the `client` field will appear as `null` when rendered in json.
> fix(filters): mark `client` and `filters` optional for merge filter

- src/filter/highlight.rs
- src/filter/sanitize.rs
This PR adds a `case_sensitive` option to the `highlight` and `sanitize` filters. By default, it is set to `false`.
When `case_sensitive` is `true` for the `highlight` filter, it will only highlight matches that have the same case as the search term.
Similarly, `case_sensitive` controls whether the `from` field of the `replace` operation in the `sanitize` filter matches the case. Note that currently, it's not possible to specify a case-sensitive `remove` operation. As a workaround, you 
can use a case-sensitive `replace` operation with `to: ""`.
Example:
```yaml
highlight:
keywords:
- foo
- bar
bg_color: '#ffff00'
case_sensitive: true
sanitize:
- remove: "foo"
- remove_regex: '\\d+'
- replace:
from: "bar"
to: "baz"
case_sensitive: true
- replace_regex:
from: '\\w+'
to: "qux" …
```
> feat: `case_sensitive` option for `highlight` and `sanitize` filter

- src/feed.rs
- src/filter/html.rs
Previously, the `split` filter is only able to generate a feed whose items has title, link, author, and description.
However, the users can also benefit from having a field for publication date. The publication date field will allow the feed readers to sort by date, and also allow the items to be sorted correctly in the `merge` filter.
This PR adds a new config field to the `split` filter named `date_selector` to enable users to select the publication date. The selector is optional, and has the same syntax as other selector fields.
One thing to note is that the code employs some heuristic to guess the publication date from the selected elements. The heuristic is as follows:
1. check the `textContent` for valid date string
2. check through all the attributes for valid date string
The …
> feat: select publication date in `split` filter

- src/feed.rs
Previously, the `merge` filter only merges the items from the other feeds. It fails in case where the merged feeds have different set of namespaces. If the source feed doesn't have the necessary namespaces used by the items from merged feeds, then the output xml will invalid. The issue was first reported in https://github.com/shouya/rss-funnel/issues/86.
This PR fixes the issue by merging the namespaces of the merged feeds into the source feed.
> fix: merge feeds with extra namespaces

- src/client/cache.rs
- src/feed.rs
- src/filter.rs
- src/filter/limit.rs
This PR adds a new filter `limit` that allows limiting the number of posts. This filter operates in two modes:
- count mode: only the first `n` posts are kept
- duration mode: only posts that are created within `duration` are kept
The format of duration string follows the same format as any other duration strings. Find more information about the duration format at [duration_str](https://docs.rs/duration-str).
The config syntax as follows:
``` yaml
- path: /hackernews-fresh.xml
source: https://news.ycombinator.com/rss
filters:
- limit: 8h
- path: /hackernews-first-10.xml
source: https://news.ycombinator.com/rss
filters:
- limit: 10
```
Fixes https://github.com/shouya/rss-funnel/issues/88.
> feat(filters): limit the number of posts

- src/feed.rs
- src/feed/extension.rs
- src/filter/full_text.rs
- src/filter/highlight.rs
- src/filter/html.rs
- src/filter/sanitize.rs
- src/filter/select.rs
- src/filter/simplify_html.rs
This PR clarifies the concept for "body" used in code and config.
Fixes https://github.com/shouya/rss-funnel/issues/95 and https://github.com/shouya/rss-funnel/issues/96.
Previously, I name a generic field in the code "description" to distinguish it from the title. For rss format it refers to the [`description` field](https://github.com/shouya/rss-funnel/blob/dc1efac19a96e06143b75e9495adb3f6b013a75f/src/feed.rs#L348) and for atom it refers to the [`content` field](https://github.com/shouya/rss-funnel/blob/dc1efac19a96e06143b75e9495adb3f6b013a75f/src/feed.rs#L368). The choice of the name and the selected fields are purely arbitrary based on the few example feeds I had in hand. Overall, it is supposed be the field that ultimately get displayed in rss feeder beneath the title.
In this PR I …
> fix: handle different body fields

- src/server/feed_service.rs
- src/util.rs
This PR adds a check so that when two endpoints has the same path, an error is raised instead of gets processed silently.
> fix: detect endpoint path collision

- Cargo.lock
- Cargo.toml
The update greatly reduces the number of duplicated dependencies because reqwest 0.12.x is built upon the same http/hyper version as I am using in the project.
> chore: upgrade reqwest to 0.12.2

- Cargo.lock
- Cargo.toml
- src/client.rs
- src/util.rs
This PR adds the `proxy` field to client config which specifies the proxy to use for any HTTP requests. The format of the value is the same as the `all_proxy` environment (see https://docs.rs/reqwest/latest/reqwest/struct.Proxy.html).
This PR contains new config fields. Documentation updated accordingly.
> feat: proxy support

- inspector/src/FeedInspector.js
- inspector/src/style.css
- src/feed.rs
- src/feed/preview.rs
- src/server/inspector.rs
Previously, the "Rendered" view was parsed from the raw XML feed on the front-end. The logic on determining which field to show as posts' bodies is arbitrary. Since #100, I changed the logic to recognize more post body types. However, such change was not reflected on the Web UI. This PR updates the Web UI to show the expected body content.
Besides, I made some visual tweaks to the Rendered view to show more information including post's publication date, feed's description, etc.
In addition, The status bar will now show the number of posts on successful fetches.
> feat: improve post body rendering on Web UI

- Cargo.lock
- Cargo.toml
- src/feed.rs
- src/feed/conversion.rs
- src/js/builtin.rs
This PR adds four new functions to the JavaScript runtime.
- `util.encode_url(string): string`
- `util.decode_url(string): string?`
- `util.encode_base64(string): string`
- `util.decode_base64(string): string?`
These functions are available in js filters including `filter_post`, `filter_feed`, and `js`.
> feat(js): add more utility functions

- Cargo.toml
- Cross.toml
- Dockerfile.armhf
- Makefile
fix for https://github.com/shouya/rss-funnel/pull/110
build for armv6-hf
with these changes command 
```
cross build -r --target arm-unknown-linux-gnueabihf
```
works and it runs, but the web part (GUI) doesn't work. But it is not a problem.
> updates to make work build on target arm-unknown-linux-gnueabihf

- src/cache.rs
- src/client.rs
- src/client/cache.rs
- src/feed.rs
- src/feed/preview.rs
- src/filter/full_text.rs
- src/main.rs
Added cache feed results after full_text filter.
It allows avoid calling try_fetch_full_post twice for the same post. So performance of application is increased from 10s to 1s on my Raspberry Pi. I think it is a huge impact.
> Cache feed results after full_text filter

- src/client.rs
- src/feed/extension.rs
- src/js.rs
I renamed the `set_cookie` field to `cookie` in the `Request` struct. The old field is now deprecated and will be removed in the next release.
> fix(client): Fix broken cookie in requests

- Cargo.lock
- Cargo.toml
- src/client.rs
This PR adds support for HTTP/2 requests that's enabled by default. The feature was added because I have a feed protected by cloudflare that triggers the anti-scraping page on HTTP/1.1 requests.
In addition, it's now possible to skip certificate verification by setting the `accepts_invalid_certs` option to `true`.
> feat(client): support http/2 requests

- src/filter.rs
- src/filter/find_magnet.rs
- src/filter/magnet.rs
This PR adds a new filter `magnet` that extracts magnet links from the body of the feed entry and store them in places bittorrent clients recognizes.
For feeds in RSS format, the magnet links will be stored in the `<enclosure>`. For feeds in Atom format, the magnet links will be stored in a new `<link>`.
The filter has two configurations:
- `info_hash` (boolean, default: false): whether or not to detect info hash by length without `magnet:` prefix. It's used when the magnet link is not directly given in the body but the info hash is somehow extractable.
- `override_existing` (boolean, default: false): if the entry already contains a magnet link in its enclosure, whether or not to override it with the detected one.
> feat(filters): detect magnet links from feed entries

- Cargo.lock
- Cargo.toml
- src/filter.rs
- src/filter/image_proxy.rs
- src/filter/merge.rs
- src/server.rs
- src/server/image_proxy.rs
- src/util.rs
This PR implements image proxy support. It contains two parts:
- an image proxy server running behind `/_image` endpoint
- a filter to rewrite image URLs to the image proxy server
See [Image proxy](https://github.com/shouya/rss-funnel/wiki/Image-proxy) page for detailed usage.
> feat: Image proxy endpoint and filter

- src/filter/image_proxy.rs
- src/server/image_proxy.rs
This PR adds rewrite support for the `srcset` attribute in the image proxy.
Fixes #125.
> feat(image-proxy): Implement srcset rewrite

- Cargo.lock
- Cargo.toml
- Makefile
- src/main.rs
Add signal hooks to shutdown the application upon receiving SIGTERM or SIGINT signals.
Fixes #129.
> fix: Graceful shutdown

- Dockerfile
- Makefile
- src/cli.rs
- src/server.rs
This PR adds a `health-check` command to the CLI. You can call `rss-funnel health-check` to check if the server is running and healthy. The Docker image now also includes the `HEALTHCHECK CMD` directive.
Internally it does a simple GET request to the `/_health` endpoint.
Options:
- `-s`/`--server`/`RSS_FUNNEL_HEALTH_CHECK_SERVER` - The server to check. Default: `http://127.0.0.1:4080`.
Closes #128.
> feat: Health check command

- Cargo.lock
- src/server/endpoint.rs
- src/util.rs
Previously, if an endpoint failed to fetch the source, the endpoint would respond with a status 500 and an error message too specific. For example, it could be a "500: bad url" which is not very clear to the user that it's the source url that's broken or an url elsewhere.
This commit improves on the error message by providing a more user-friendly message:
- http request errors from anywhere in the pipeline will show as a 502 error with the failed status code and the requesting url is returned in the error message
- source errors will indicate it's a source error
> fix: improve source error message

- src/filter.rs
- src/filter/image_proxy.rs
- src/filter/merge.rs
- src/server/endpoint.rs
- src/source.rs
- src/util.rs
This PR adds support for placeholders in the source url. This is useful for cases where the portion of source url is dynamic and can be specified when users request for the endpoint. The feature can be considered a pragmatic middle ground between static source and dynamic source.
Implements the feature request in https://github.com/shouya/rss-funnel/issues/137.
Here's an example to demonstrate the usage:
```yaml
endpoints:
- path: /telegram.xml
source:
template: https://bridge.easter.fr/?action=display&bridge=TelegramBridge&username=${username}&format=Atom
placeholders:
username: {}
filters: []
```
For each placeholders, you can define the default value and/or a validation regex:
```yaml
endpoints:
- path: /telegram.xml
source:
template: …
```
> feat: Placeholders in source

- src/server/endpoint.rs
- src/server/image_proxy.rs
Previously the `filters` key is required for an `endpoint` definition. Now we have cases where the `filters` are no longer needed:
- endpoints with on-the-fly filters
- endpoints merely meant to proxy upstream feeds (for example, with templated source)
In such cases, we should allow the user to omit the unncessary `filters` key altogether.
> fix: Allow unspecified filters key

- scripts/watch-dev.sh
- src/filter.rs
- src/server/endpoint.rs
- src/server/web/endpoint.rs
- src/server/web/list.rs
- src/source.rs
- src/util.rs
Previously dynamic source is represented as `Option<Source>`. Upon reflection, the case for dynamic source is not semantically the case for the lack of source despite a null source is how dynamic source is represented in config. Therefore, it is better to represent dynamic source as a variant of `Source`.
> refactor: improve source representation

- src/feed.rs
- src/feed/preview.rs
- src/filter/merge.rs
- src/source.rs
Fix https://github.com/shouya/rss-funnel/issues/143.
For `merge` filter, feeds that failed to fetch will no longer fail the entire endpoint. Instead an error feed item is appended to the endpoint's output.
> fix(filter): handle feed errors for merge filter

- src/server/endpoint.rs
- src/server/web.rs
- src/server/web/endpoint.rs
I found that the image proxy is not applied when requested through web ui. The cause is that the endpoint parameter is not extracted correctly, such that the `base` field is always missing. This PR fixes the issue.
In addition I realized the app base inference logic doesn't match what's defined in the documentation. I've updated the logic to match the documentation.
> fix: image proxy on web ui

- src/filter.rs
- src/filter/js.rs
- src/filter/merge.rs
- src/filter_pipeline.rs
- src/js.rs
- src/js/builtin.rs
- src/otf_filter.rs
- src/server/endpoint.rs
- src/server/web/endpoint.rs
This PR combines two features:
- make `console.{log,error}` outputs more clear (fixes #152)
- show js logs on webui (fixes #71)
Screenshot:
Note: due to [the way caching is implemented](https://github.com/shouya/rss-funnel/pull/153), refreshing the webpage without changing the config may skip js evaluation, thus the log may not show up as expected.
> feat: js logs on webui

- src/cli.rs
- src/filter/image_proxy.rs
- src/filter/merge.rs
- src/server.rs
- src/server/auth.rs
- src/server/endpoint.rs
- src/server/feed_service.rs
- src/server/image_proxy.rs
- src/server/web.rs
- src/server/web/endpoint.rs
- src/server/web/list.rs
- src/server/web/login.rs
- src/util.rs
fixes #159.
The path prefix is inferred by the following order:
1. The environment `RSS_FUNNEL_PATH_PREFIX` (Example value: `"app/"`), or if unspecified
2. The path of environment `RSS_FUNNEL_APP_BASE`, or if unspecified
3. `"/"`.
> Support hosting service on non-root path prefix

- src/server/web/list.rs
#160 introduced a bug where the endpoint links in the list view were not pointing to the right place. This PR fixes that.
fixes #161.
> fix (web): endpoint links in list view
